version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-15.7
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - recursion-algorithms-{{ checksum "recursion-algorithms.cabal" }}-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack setup
      - run:
          name: Run tests
          command: stack test
      - save_cache:
          name: Cache Dependencies
          key: recursion-algorithms-{{ checksum "recursion-algorithms.cabal" }}-{{ checksum "stack.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
