name: Test
on: push
jobs:
  doctest:
    name: Run all doctest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: |
            ~/.stack
            .stack-work
          key: recursion-algorithms-${{ hashFiles('package.yaml') }}-${{ hashFiles('stack.yaml') }}
      - uses: haskell/actions/setup@v1
        with:
          enable-stack: true
          stack-no-global: true
          stack-setup-ghc: true
      - run: ls
      - run: pwd
      - run: stack test
