name: Test
on: push
jobs:
  doctest:
    name: Run all doctest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          enable-stack: true
      - run: |
          pwd
          ls
      - run: stack setup
      - run: stack test
